#
# Copyright 2019 JSquad AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


openapi: 3.0.0

info:
  title: Jsquad OpenBank API
  description: Bank OpenAPI
  version: 0.0.3

servers:
  - url: http://localhost:8080/restful-webservice/api
    description: Local OpenBank server

paths:
  /client/account/transfer/{value}/{fromAccountNumber}/{toAccountNumber}:
    put:
      summary: Transfer money from one account to another account
      parameters:
        - in: path
          name: value
          schema:
            example: 250
            type: integer
          required: true
        - in: path
          name: fromAccountNumber
          schema:
            type: string
            example: '1051'
          required: true
        - in: path
          name: toAccountNumber
          schema:
            type: string
            example: '1050'
          required: true
      responses:
        '200':
          description: Returns an ok if transfer was succesful
          content:
            application/json:
              schema:
                type: string
                example: 'Transaction successful.'
        '401':
          description: Returns a unauthorized message
          content:
            application/json:
              schema:
                type: string
                example: 'Authorization failed.'
        '5XX':
          description: Unexpected system error
          content:
            application/json:
              schema:
                example: 'System failure'
                type: string
  /client/create/:
    post:
      summary: Create client
      requestBody:
        description: Client model as request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '200':
          description: Returns an ok and message string
          content:
            application/json:
              schema:
                example: 'Client successfully created'
                type: string
        '400':
          description: Client data has not valid format
          content:
            application/json:
              schema:
                example: 'Client with personIdentificaton is wrong format\n and firstName is in wrong format'
                type: string
        '401':
          description: Returns a unauthorized message
          content:
            application/json:
              schema:
                type: string
                example: 'Authorization failed.'
        '5XX':
          description: Unexpected system error.
          content:
            application/json:
              schema:
                example: 'System failure.'
                type: string

  /client/login:
    get:
      summary: Returns a ok status that login was successful
      description: Returns status messages if login went successful or not
      responses:
        '200':
          description: Returns a ok JSON message
          content:
            application/json:
              schema:
                type: string
                example: 'Authorization ok.'
        '401':
          description: Returns a unauthorized message
          content:
            application/json:
              schema:
                type: string
                example: 'Authorization failed.'
        '5XX':
          description: Returns a server failure
          content:
            application/json:
              schema:
                type: string
                example: 'Severe system error has occured.'

  /client/logout:
    get:
      summary: Returns a ok status that login was successful
      description: Returns status messages if login went successful or not
      responses:
        '200':
          description: Returns a ok JSON message
          content:
            application/json:
              schema:
                type: string
                example: 'Logout successful.'
        '5XX':
          description: Returns a server failure
          content:
            application/json:
              schema:
                type: string
                example: 'Severe system error has occured.'


  /client/info/{personIdentification}:
    parameters:
      - in: path
        name: personIdentification
        schema:
          type: string
          example: '191212121212'
        required: true
        description: Client's identification number
    get:
      summary: Returns a Client object with all related list of account data if you are admin
      description: Returns a client object
      responses:
        '200':
          description: Returns a JSON Client object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
        '401':
          description: Returns a unauthorized message
          content:
            application/json:
              schema:
                type: string
                example: 'Authorization failed.'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '5XX':
          description: Unexpected system error.
          content:
            application/json:
              schema:
                example: 'System failure.'
                type: string

  /openbank/hello/world:
    get:
      summary: Returns a string with 'hello world'
      description: Returns a hello world string
      responses:
        '200':
          description: Returns a JSON string with hello world
          content:
            application/json:
              schema:
                example: 'Hello world'
                type: string
        '5XX':
          description: Unexpected system error.
          content:
            application/json:
              schema:
                example: 'System failure.'
                type: string

  /openbank/start/slow/batch/mock:
    get:
      summary: Returns a BatchStatus object with status enum and message string.
      description: Returns a BatchStatus object
      responses:
        '200':
          description: Returns a BatchStatus JSON string.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchStatus'
        '5XX':
          description: Unexpected system error.
          content:
            application/json:
              schema:
                example: 'System failure.'
                type: string

components:
  schemas:
    BatchStatus:
      type: object
      properties:
        status:
          type: string
          enum: [SUCCESS, FAIL]
          example: 'SUCCESS'
        message:
          type: string
          example: 'Batch job went well.'

    Client:
      type: object
      properties:
        person:
          $ref: '#/components/schemas/Person'
        accountList:
          type: array
          items:
            $ref: '#/components/schemas/Account'
        clientType:
          $ref: '#/components/schemas/ClientType'

    ClientType:
      type: object
      properties:
        type:
          type: string
          enum: [REGULAR, PREUMIUM, FOREIGN]
          example: 'REGULAR'
        specialOffers:
          type: string
          example: 'Don Vito has an offer we can not refuse.'
        rating:
          type: integer
          example: 10000
        premiumRating:
          type: integer
          example: 99999
        country:
          type: string
          example: 'Italy'

    Person:
      type: object
      properties:
        personIdentification:
          type: string
          example: 197501011234
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        mail:
          type: string
          example: 'john.doe@test.se'
        addressList:
          type: array
          items:
            $ref: '#/components/schemas/Address'

    Address:
      type: object
      properties:
        country:
          type: string
          example: 'Sweden'
        municipality:
          type: string
          example: 'Stockholm county'
        postalCode:
          type: integer
          example: 17211
        street:
          type: string
          example: 'Valhallavägen'
        streetNumber:
          type: integer
          example: 12

    Account:
      type: object
      properties:
        balance:
          type: integer
          example: 59765
        accountTransactionList:
          type: array
          items:
            $ref: '#/components/schemas/AccountTransaction'

    AccountTransaction:
      type: object
      properties:
        transactionType:
          type: string
          enum: [DEPOSIT, WITHDRAWAL]
          example: 'DEPOSIT'
        message:
          type: string
          example: 'Deposit 500$'

    NotFound:
      type: object
      properties:
        status:
          type: integer
          example: 404
        type:
          type: string
          example: 'ClientNotFound'
        message:
          type: string
          example: 'Client not found.'

