openapi: 3.0.0

info:
  title: Jsquad OpenBank API
  description: Bank OpenAPI
  version: 0.0.2

servers:
  - url: http://localhost:8080/restful-webservice/api
    description: Local OpenBank server

paths:
  /client/create/:
    post:
      summary: Create client
      requestBody:
        description: Client model as request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '200':
          description: Returns an ok and message string
          content:
            application/json:
              schema:
                example: 'Client successfully crated'
                type: string
        '400':
          description: Client data has not valid format
          content:
            application/json:
              schema:
                example: 'Client with personIdentificaton is wrong format\n and firstName is in wrong format'
                type: string
        '5XX':
          description: Unexpected system error

  /client/info/{personIdentification}:
    parameters:
      - in: path
        name: personIdentification
        schema:
          type: string
        required: true
        description: Client's identification number
    get:
      summary: Returns a Client object with all related list of account data
      description: Returns
      responses:
        '200':
          description: Returns a JSON Client object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '5XX':
          description: Unexpected system error.

  /openbank/hello/world:
    get:
      summary: Returns a string with 'hello world'
      description: Returns a hello world string
      responses:
        '200':
          description: Returns a JSON string with hello world
          content:
            application/json:
              schema:
                example: 'Hello world'
                type: string
        '5XX':
          description: Unexpected system error.

  /openbank/start/slow/batch/mock:
    get:
      summary: Returns a BatchStatus object with status enum and message string.
      description: Returns a BatchStatus object
      responses:
        '200':
          description: Returns a BatchStatus JSON string.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchStatus'
        '5XX':
          description: Unexpected system error.

components:
  schemas:
    BatchStatus:
      type: object
      properties:
        status:
          type: string
          enum: [SUCCESS, FAIL]
          example: 'SUCCESS'
        message:
          type: string
          example: 'Batch job went well.'

    Client:
      type: object
      properties:
        person:
          $ref: '#/components/schemas/Person'
        accountList:
          type: array
          items:
            $ref: '#/components/schemas/Account'
        clientType:
          $ref: '#/components/schemas/ClientType'

    ClientType:
      type: object
      properties:
        type:
          type: string
          enum: [REGULAR, PREUMIUM, FOREIGN]
          example: 'REGULAR'
        specialOffers:
          type: string
          example: 'Don Vito has an offer we can not refuse.'
        rating:
          type: integer
          example: 10000
        premiumRating:
          type: integer
          example: 99999
        country:
          type: string
          example: 'Italy'

    Person:
      type: object
      properties:
        personIdentification:
          type: string
          example: 197501011234
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        mail:
          type: string
          example: 'john.doe@test.se'

    Account:
      type: object
      properties:
        balance:
          type: integer
          example: 59765
        accountTransactionList:
          type: array
          items:
            $ref: '#/components/schemas/AccountTransaction'

    AccountTransaction:
      type: object
      properties:
        transactionType:
          type: string
          enum: [DEPOSIT, WITHDRAWAL]
          example: 'DEPOSIT'
        message:
          type: string
          example: 'Deposit 500$'

    NotFound:
      type: object
      properties:
        status:
          type: integer
          example: 404
        type:
          type: string
          example: 'ClientNotFound'
        message:
          type: string
          example: 'Client not found.'

